# Generated by Django 3.2.9 on 2021-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('indoor', models.BooleanField()),
                ('outdoor', models.BooleanField()),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
