# Generated by Django 3.2.9 on 2021-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='description',
            field=models.TextField(default='no review'),
        ),
        migrations.AddField(
            model_name='seat',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='rating',
            field=models.CharField(default='no rating', max_length=100),
        ),
        migrations.AddField(
            model_name='seat',
            name='reviewer',
            field=models.CharField(default='no reviewer', max_length=100),
        ),
        migrations.AddField(
            model_name='seat',
            name='slocation',
            field=models.CharField(default='no seat location', max_length=100),
        ),
    ]
